version: '3.9'

services:
    mysql:
        image: bitnami/mysql:8.0
        ports:
            - "3306:3306"
        volumes:
            - ./mysql:/bitnami/mysql/data
        environment:
            MYSQL_ROOT_PASSWORD: 123
            MYSQL_DATABASE: warehouse
            MYSQL_USER: warehouse
            MYSQL_PASSWORD: 123
            MYSQL_AUTHENTICATION_PLUGIN: mysql_native_password
    app:
        build:
            context: .
            dockerfile: php.dockerfile
        volumes:
            - ./../:/var/www/html
        ports:
            - "8000:8000"
        depends_on:
            - mysql
        entrypoint: [ "php", "/var/www/html/artisan", "serve", "--host=0.0.0.0" ]
    artisan:
        build:
            context: .
            dockerfile: php.dockerfile
        volumes:
            - ./../:/var/www/html
        depends_on:
            - mysql
        entrypoint: [ "php", "artisan" ]
    composer:
        build:
            context: .
            dockerfile: php.dockerfile
        volumes:
            - ./../:/var/www/html
            - ./composer:/root/.composer
        entrypoint: [ "composer" ]
